### ISSUE TITLE
Ability to DM user

### ISSUE THREAD

**Issue by saitheexplorer** [Joezo/node-slackhook#2]
`if(channel.substring(0,1) !== '#') channel = '#' + channel;` (line 22 in slack.js) is preventing me from being able to DM a user using this webhook - commenting out this line makes it work.

Thoughts on enabling that functionality? Let me know and I can create a pull request if you're cramped for time.

**Comment by Joezo** [comment]
Please do put a pull request in :) I think we can change this, i'll put a note in the release notes about the potential breaking change

**Comment by Joezo** [comment]
Closed as merged #3
